spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 12345678
#    url: jdbc:mysql://127.0.0.1:3306/oop?characterEncoding=utf-8&useSSL=false
    username: lengfeng
    password: lengfeng1234
    url: jdbc:mysql://115.159.37.150:3306/oop?characterEncoding=utf-8&useSSL=false

mybatis:
  # model的包
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.oop.model
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

server:
  port: 12306

wechat:
  mpAppId: wx21a0162088a3da01
  mpAppSecret: ad33b806611dda97866427947727b9d5

#  # 通用Mapper配置
#  mapper.plugin = tk.mybatis.mapper.generator.MapperPlugin
#  mapper.Mapper = tk.mybatis.mapper.common.Mapper
#
#  #mappers 多个接口时逗号隔开
#  mapper.mappers=tk.mybatis.mapper.common.Mapper
#  mapper.not-empty=false

#  mapper.identity=MYSQL