<html>
<#include "common/header.ftl">

<body>
<div id="wrapper" class="toggled">

<#--边栏sidebar-->
<#include "common/nav.ftl">
    <div id="page-content-wrapper">
        <div class="container-fluid">
        <div class="jumbotron">
            <h1>面向对象作业使用</h1>
            <p>...</p>
            <p><a class="btn btn-primary btn-lg" href="/seller/product/list" role="button">查看商品</a></p>
        </div>
        </div>
    </div>



</div>
</body>
</html>